Repository sats-group/sats-dna-android, pull requests merged in 2023-11, with the labels that each got.

#247 NMA-5783: Animated Checkmark
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/IconsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/AnimatedCheckmark.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/SatsIcons.kt
  sats-dna/src/main/res/drawable/ic_check_thin.xml
Labels: breaking

#248 NMA-5809: Delete Recruit Friends icons
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/IconsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/SatsIcons.kt
  sats-dna/src/main/res/drawable/ic_recruit_friends.xml
  sats-dna/src/main/res/drawable/ic_share.xml
Labels: refactor, breaking

#250 NMA-5831: Re-implement the Design System typography
  .github/workflows/ci.yml
  gradle/libs.versions.toml
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/BottomNavigationSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChipsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/PlaceholdersSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SurfaceSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TagsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt
  sats-dna/build.gradle.kts
  sats-dna/src/main/kotlin/com/sats/dna/components/CompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/Placeholders.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCampaignModule.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/icons/DefaultInstructorIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/navigation/BottomNavigation.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/Schedule.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutContent.kt
  sats-dna/src/main/kotlin/com/sats/dna/theme/SatsTheme.kt
  sats-dna/src/main/kotlin/com/sats/dna/typography/InterFont.kt
  sats-dna/src/main/kotlin/com/sats/dna/typography/SatsTypography.kt
  sats-dna/src/main/kotlin/com/sats/dna/typography/SatsTypographyPreview.kt
  settings.gradle.kts
Labels: enhancement, breaking

#254 NMA-5845: Bump Kotlin to 1.9.20
  gradle/libs.versions.toml
Labels: dependencies
