Repository sats-group/sats-dna-android, pull requests merged in 2024-05, with the labels that each got.

#452 NMA-6675: Add datetime and text field placeholders
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFormInputFields.kt
Labels: enhancement

#465 NMA-6704: Bump Compose BoM to 2024.05.00-alpha01
  gradle/libs.versions.toml
Labels: dependencies

#464 NMA-6703: Fix scrolled container color for top app bars
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt
Labels: bugfix

#450 NMA-6667: Fade top app bars between screens
  sample-app/src/main/kotlin/com/sats/dna/sample/MainActivity.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/internal/SharedTransitions.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
Labels: enhancement

#466 NMA-6705: Fix content color for primary disabled button
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt
Labels: bugfix

#468 NMA-6714: Some color changes and fixes
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/styles/ColorsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
Labels: enhancement

#470 NMA-6719: Update article card to support news
  sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsArticleCard.kt
Labels: enhancement

#471 NMA-6736: Don't apply modifier twice in icon button
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
Labels: bugfix, breaking

#472 NMA-6730: Remove SatsScreen
  sample-app/src/main/kotlin/com/sats/dna/sample/internal/SatsScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/components/ChallengeBackgroundSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/components/FancyTopAppBarSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBarVisuals.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
Labels: breaking

#477 NMA-6741: Bump Kotlin to version 1.9.24
  gradle/libs.versions.toml
Labels: dependencies

#478 NMA-6741: Use non-experimental strong skipping flag
  sats-dna/build.gradle.kts
Labels: bugfix

#479 NMA-6751: Update colors from color system
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/styles/ColorsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
Labels: enhancement

#483 NMA-6764: Add new icons
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/icons/IconsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/Attachment.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/ClassFilled.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/Exorlive.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/SearchCrossed.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/ThumbsDown.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/TiktokPadding.kt
  scripts/figma-icons/package-lock.json
Labels: enhancement

#486 NMA-6776: Add article card placeholder sample
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/components/ArticleCardSampleScreen.kt
Labels: enhancement

#484 NMA-6773: Change light mode disabled colors to new Black 55 primitive
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorPrimitives.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
Labels: enhancement
