Repository sats-group/sats-dna-android, pull requests merged in 2024-04, with the labels that each got.

#434 NMA-6595: Use the same layout for all buttons
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ArticleCardSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonAnimation.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColorProvider.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonIconContent.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonSize.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButtonContent.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsLikeButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsTopAppBarIconButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/internal/IconButtonContentSize.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/internal/IconButtonPadding.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/internal/MinContentSize.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/internal/PreviewBackgroundColor.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/internal/SatsBaseButtonLayout.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/internal/SatsIconButtonContent.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/internal/SatsTextButtonContent.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsArticleCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsChallengeCard.kt
Labels: refactor, breaking

#428 NMA-6589: Bump Compose to version 1.7.0-alpha06
  gradle/libs.versions.toml
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/FormInputFieldsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFormInputFields.kt
Labels: refactor, breaking

#435 NMA-6601: Some sample app home screen stuff
  sample-app/build.gradle.kts
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
Labels: enhancement

#441 NMA-6634: Use new alpha release of androidx.navigation
  gradle/libs.versions.toml
Labels: enhancement

#437 NMA-6629: Update colors to match design system
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CheckboxSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ColorsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorPrimitives.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCheckbox.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsRadioButton.kt
Labels: refactor, breaking

#443 Simplify color creation a bit
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
Labels: refactor

#444 NMA-6638: Rewrite colors sample screen
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ColorsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
Labels: bugfix, enhancement, refactor, breaking

#445 NMA-6639: Add Fixed Action button color
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ColorsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
Labels: enhancement

#446 NMA-6642: Delete unused icons
  sats-dna/src/main/res/drawable/ic_elixia.xml
  sats-dna/src/main/res/drawable/ic_letter_e.xml
  sats-dna/src/main/res/drawable/ic_letter_s.xml
  sats-dna/src/main/res/drawable/ic_qr.xml
  sats-dna/src/main/res/drawable/ic_refresh.xml
  sats-dna/src/main/res/drawable/ic_sats.xml
Labels: refactor

#447 NMA-6644: Fix selector component colors
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCheckbox.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsRadioButton.kt
Labels: bugfix

#448 NMA-6655: Fix unselected chip border colors
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsChip.kt
Labels: bugfix

#451 NMA-6668: Remove useMaterial3 parameter from SatsSurface
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ColorsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/DividersSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/FancyTopAppBarSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/JoinYourFriendsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ScaleBarSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SearchBarSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SurfaceSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TitledSectionSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/YourMostBookedSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsAnimatedCheckmark.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBadge.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBrandLogo.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsChallengeBackground.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCheckbox.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsChip.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCircularProgressIndicator.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsDivider.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFancyTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFormInputFields.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsGeneralListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsGxSessionImage.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsImagePlaceholder.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsJoinYourFriendsCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsPill.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsPlaceholders.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsProfileAvatarImage.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsRadioButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsScaleBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSurface.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSwitch.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTabRow.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTag.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledSection.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTrafficLight.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsWorkoutTypeColorIndicator.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsYourMostBookedCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsLargeTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsTopAppBarIconButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/chip/SatsChip.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/icons/SatsDefaultInstructorIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/internal/GxSessionCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/statistics/SatsWorkoutGraph.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/statistics/SatsWorkoutStatisticsCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsSchedule.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsUpcomingWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SharedComponents.kt
  sats-dna/src/main/kotlin/com/sats/dna/shapes/SatsShapes.kt
Labels: refactor, breaking

#457 NMA-6684: Downgrade Compose to 1.7.0-alpha06
  gradle/libs.versions.toml
Labels: bugfix, breaking

#455 NMA-6682: Ensure fancy top app bar expanded between 0f..1f
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/FancyTopAppBarSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFancyTopAppBar.kt
Labels: bugfix, breaking

#456 NMA-6683: Fix color of profile avatar image fallback
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsProfileAvatarImage.kt
Labels: bugfix
