Repository sats-group/sats-dna-android, pull requests merged in 2024-03, with the labels that each got.

#366 NMA-6316: Remove Transparent button color and change Action
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/UpcomingWorkoutListItemSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutListItem.kt
Labels: bug, breaking

#370 NMA-6320: Create template for GitHub changelogs
  .github/release.yml
  .github/renovate.json
Labels: devops

#367 NMA-6321: Remove Material 2-based top app bar
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TopAppBarSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/LargeTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/TopAppBar.kt
Labels: refactor, breaking

#368 NMA-6324: Change to new colors from design system
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CheckboxSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/GeneralListItemSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorPrimitives.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsContentColorFor.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/ChallengeBackground.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/CompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCheckbox.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFormInputFields.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSwitch.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTag.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/LargeTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/TopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/CardButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/LikeButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/icons/WorkoutTypeIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SessionDetailsInfoLabel.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutContent.kt
  sats-dna/src/main/kotlin/com/sats/dna/shapes/SatsShapes.kt
Labels: refactor, breaking

#369 NMA-6325: Remove M2-based SATS Screen component
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/CompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
Labels: refactor, breaking

#371 NMA-6326: Remove M2-based text field components
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TextFieldSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsOutlinedTextField.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTextField.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SessionDetailsInfoLabel.kt
  sats-dna/src/main/kotlin/com/sats/dna/internal/MaterialIcon.kt
Labels: refactor, breaking

#372 NMA-6327: Prefix all design system components with “Sats”
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/internal/SamplePictures.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/BottomNavigationSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/BrandLogoSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CardSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CompletedWorkoutListItemSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/FriendsBookingStatusSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/JoinYourFriendsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/PlaceholdersSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ScheduleSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SessionDetailsInfoLabelSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TopAppBarSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TrafficLightsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/UpcomingWorkoutListItemSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/YourMostBookedSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/LocalUseMaterial3.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsAnimatedCheckmark.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBrandLogo.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCampaignModule.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsChallengeBackground.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsChallengeBadge.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsGxSessionImage.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsJoinYourFriendsCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsPill.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsPlaceholders.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsProfileAvatarImage.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSurface.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTag.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTrafficLight.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsYourMostBookedCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsLargeTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsCardButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsLikeButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/chip/SatsChip.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/icons/SatsDefaultInstructorIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/icons/SatsWorkoutTypeIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/internal/GxSessionCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/navigation/BottomNavigation.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/progressbar/SatsLinearProgressBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SatsFriendsBookingStatusListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SatsSessionDetailsInfoSection.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsSchedule.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsUpcomingWorkout.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsUpcomingWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsWorkoutTypeColorIndicator.kt
  sats-dna/src/main/kotlin/com/sats/dna/internal/MaterialIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/internal/MaterialText.kt
Labels: refactor, breaking

#378 NMA-6414: Change fixed progress bar background to White 40
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
Labels: enhancement

#377 NMA-6416: Alias snackbar stuff to protein bar equivalents
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBarVisuals.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
Labels: refactor

#380 NMA-6418: Put clean button previews behind fixed backgrounds
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
Labels: bugfix

#381 NMA-6416: Add missing protein bar result typealias
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
Labels: enhancement

#379 NMA-6417: Fix border color of unselected chips
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsChip.kt
Labels: bugfix

#374 NMA-6335: Create new button components with proper sizing
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TopAppBarSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/UpcomingWorkoutListItemSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSearchBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsLargeTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColorProvider.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonIconContent.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonSize.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsUpcomingWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/typography/SatsTypography.kt
Labels: enhancement, refactor

#384 NMA-6302: Use small button for challenge cards
  sats-dna/src/main/kotlin/com/sats/dna/components/card/ChallengeCard.kt
Labels: bugfix

#385 NMA-6425: Use new icon button for titled cards
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledCard.kt
Labels: bugfix

#387 NMA-6421: Create new Titled Section component
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TitledSectionSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledSection.kt
Labels: enhancement

#386 NMA-6426: Remove old button component
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/UpcomingWorkoutListItemSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSearchBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/card/ChallengeCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsUpcomingWorkoutListItem.kt
Labels: refactor, breaking

#388 NMA-6421: Use correct button in titled section
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledSection.kt
Labels: bugfix

#390 NMA-6452: Expose top app bar container color
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsLargeTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt
Labels: bugfix

#392 NMA-6439: Add slot for image in fancy top app bar
  sample-app/build.gradle.kts
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/FancyTopAppBarSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFancyTopAppBar.kt
Labels: enhancement

#393 NMA-6462: Campaign Module -> new Article Card component
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ArticleCardSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CampaignModuleSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeCardSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCampaignModule.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/card/ChallengeCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsArticleCard.kt
Labels: breaking

#394 NMA-6422: Remove SatsSurface from General List Item
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/GeneralListItemSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCircularProgressIndicator.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsGeneralListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSearchBar.kt
Labels: bugfix, breaking

#395 NMA-6468: Remove some old colors
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ColorsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsDark.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsLight.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsContentColorFor.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SatsFriendsBookingStatusListItem.kt
Labels: breaking

#398 Add content color for signal surface featured
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsContentColorFor.kt
Labels: enhancement

#397 NMA-6475: Add scroll connection to sample screen top app bar
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
Labels: enhancement

#399 NMA-6476: Set correct signal surface bg in dark mode
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
Labels: bugfix

#396 NMA-6473: Reduce line heights for placeholder paragraph
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsPlaceholders.kt
Labels: enhancement

#401 NMA-6482: Update color system to the latest from Figma
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorPrimitives.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsContentColorFor.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
Labels: bugfix, breaking

#403 NMA-6487: Add workout graph and statistics cards
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/WorkoutStatisticsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/statistics/SatsWorkoutGraph.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/statistics/SatsWorkoutStatisticsCard.kt
Labels: refactor

#405 NMA-6500: Download all Figma icon SVGs through a script
  scripts/.gitignore
  scripts/download-figma-icons.js
  scripts/package-lock.json
  scripts/package.json
Labels: enhancement

#406 NMA-6500: Generate Android Vector Drawables from SVGs
  scripts/.gitignore
  scripts/convert-svg-files-to-vector-drawables.js
  scripts/package-lock.json
  scripts/package.json
Labels: enhancement

#407 NMA-6500: Generate SatsIcons.kt from vector drawable files
  scripts/.gitignore
  scripts/generate-sats-icons-from-vector-drawables.js
Labels: enhancement

#408 NMA-6500: Move generated files to :sats-dna
  scripts/move-icons-to-dna.js
Labels: enhancement

#409 NMA-6500: Run Figma icon scripts in succession
  scripts/.gitignore
  scripts/figma-icons/.gitignore
  scripts/figma-icons/00_run.js
  scripts/figma-icons/01_download-figma-icons.js
  scripts/figma-icons/02_convert-svg-files-to-vector-drawables.js
  scripts/figma-icons/03_generate-sats-icons-from-vector-drawables.js
  scripts/figma-icons/04_move-icons-to-dna.js
  scripts/figma-icons/package-lock.json
  scripts/figma-icons/package.json
Labels: enhancement

#411 NMA-6509: Fix shape and padding in challenge card. And prefix it with sats
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeCardSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsChallengeCard.kt
Labels: bugfix

#413 NMA-6514: Bump Kotlin to version 1.9.23
  gradle/libs.versions.toml
Labels: dependencies

#414 NMA-6515: Enable Compose strong skipping
  sats-dna/build.gradle.kts
Labels: enhancement

#417 NMA-6527: Remove space from .editorconfig file pattern
  .editorconfig
Labels: bugfix

#418 NMA-6528: Remove unused stuff
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorPrimitives.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
  sats-dna/src/main/res/drawable/ic_nav_activity_filled.xml
  sats-dna/src/main/res/drawable/ic_nav_activity_outlined.xml
  sats-dna/src/main/res/drawable/ic_nav_book_filled.xml
  sats-dna/src/main/res/drawable/ic_nav_book_outlined.xml
  sats-dna/src/main/res/drawable/ic_nav_clubs_filled.xml
  sats-dna/src/main/res/drawable/ic_nav_clubs_outlined.xml
  sats-dna/src/main/res/drawable/ic_nav_home_elixia_filled.xml
  sats-dna/src/main/res/drawable/ic_nav_home_elixia_outlined.xml
  sats-dna/src/main/res/drawable/ic_nav_home_sats_filled.xml
  sats-dna/src/main/res/drawable/ic_nav_home_sats_outlined.xml
  sats-dna/src/main/res/drawable/ic_nav_qr_filled.xml
  sats-dna/src/main/res/drawable/ic_nav_qr_outlined.xml
Labels: bugfix

#415 NMA-6520: Remove workout type icon in favor of bar
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CompletedWorkoutListItemSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/IconsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/SatsIcons.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsWorkoutTypeColorIndicator.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/icons/SatsWorkoutTypeIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsSchedule.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsUpcomingWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SharedComponents.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/WorkoutGymFloor.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/WorkoutOther.kt
Labels: refactor, breaking

#420 NMA-6537: Fix issue with long names in invitee list items
  sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SatsFriendsBookingStatusListItem.kt
Labels: bugfix

#421 NMA-6540: Import icon extensions
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CardSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/EmptyStateSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/FancyTopAppBarSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/GeneralListItemSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SessionDetailsInfoLabelSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TopAppBarSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/SatsIcons.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsChip.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFancyTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsGeneralListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSearchBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSwitch.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledCard.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledSection.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsLargeTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsCardButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsLikeButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/progressbar/SatsCircularSteppedProgressIndicator.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBarVisuals.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SatsSessionDetailsInfoSection.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/statistics/SatsWorkoutGraph.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsSchedule.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/FistBumpIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/SatsIcons.kt
  sats-dna/src/main/kotlin/com/sats/dna/internal/MaterialIcon.kt
Labels: bugfix

#422 NMA-6541: Remove deprecated button typography
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFancyTopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/typography/SatsTypography.kt
Labels: breaking

#423 NMA-6543: Use colors from the new design system
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ColorsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/icons/SatsDefaultInstructorIcon.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SatsFriendsBookingStatusListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/statistics/SatsWorkoutGraph.kt
  sats-dna/src/main/kotlin/com/sats/dna/theme/SatsTheme.kt
Labels: refactor

#425 NMA-6544: Bring back the CTA button
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
Labels: enhancement
