Repository sats-group/sats-dna-android, pull requests merged in 2024-02, with the labels that each got.

#334 NMA-6162: Use correct colors for checkboxes
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CheckboxSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsCheckbox.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTriStateCheckbox.kt
Labels: bug, enhancement

#337 NMA-6174: Use divider component from design system
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ScheduleSampleScreen.kt
Labels: enhancement

#336 NMA-6161: Use error icon for error protein bars
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/IconsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBarVisuals.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/SatsIcons.kt
  sats-dna/src/main/res/drawable/ic_error.xml
Labels: enhancement

#343 Get compose-material3 1.2.0 from BoM
  gradle/libs.versions.toml
Labels: dependencies

#339 NMA-6189: Add new On Surface Featured color
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
Labels: enhancement

#348 NMA-6218: Fix headline line heights
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/typography/SatsTypography.kt
Labels: bug

#351 NMA-6247: Increase icon size for empty state component
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
Labels: bug

#355 NMA-6252: Remove own multi-preview annotations
  sats-dna/src/main/kotlin/com/sats/dna/tooling/PreviewAnnotations.kt
Labels: refactor, breaking

#358 NMA-6267: Remove unused hover colors
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsContentColorFor.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
Labels: refactor, breaking

#354 NMA-6255: Create new circular stepped progress indicator
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CircularProgressIndicatorSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ProgressBarsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/progressbar/SatsCircularSteppedProgressIndicator.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/progressbar/SatsLinearProgressBar.kt
Labels: enhancement

#356 NMA-6265: Create new form field components
  gradle/libs.versions.toml
  sample-app/build.gradle.kts
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/FormInputFieldsSampleScreen.kt
  sats-dna/build.gradle.kts
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsFormInputFields.kt
Labels: enhancement

#360 NMA-6273: Fix bundling sample app release
  gradle/libs.versions.toml
  sats-dna/build.gradle.kts
Labels: bug

#363 NMA-6288: Fix vertical alignment and click area
  sats-dna/src/main/kotlin/com/sats/dna/components/button/CardButton.kt
Labels: refactor

#364 NMA-6301: Create challenge background component
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/ChallengeBackground.kt
  sats-dna/src/main/res/drawable/challenge_background_top.xml
Labels: enhancement
