Repository sats-group/sats-dna-android, pull requests merged in 2024-01, with the labels that each got.

#292 NMA-5956: Set `isLightMode` correctly in dark mode
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
Labels: bug

#293 NMA-5956: Fix Material 3 Top App Bar colors
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/TopAppBar.kt
Labels: bug

#294 Fix colors in GX Session Card component
  sats-dna/src/main/kotlin/com/sats/dna/components/internal/GxSessionCard.kt
Labels: bug

#295 NMA-5965: Fix GX Session Card constraints
  sats-dna/src/main/kotlin/com/sats/dna/components/JoinYourFriends.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/internal/GxSessionCard.kt
Labels: bug

#297 NMA-5975: Create a large top app bar component
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TopAppBarSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TopBarSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/LargeTopAppBar.kt
Labels: enhancement

#298 NMA-5998: Ignore too-large-vector warning
  sats-dna/src/main/res/drawable/ic_elixia.xml
Labels: enhancement

#299 NMA-6012: Fix default content color for SatsBanner in dark mode
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
Labels: bug

#300 NMA-6014: Restrict the SatsBanner API surface
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
Labels: refactor

#301 NMA-6014: Use non-deprecated Banner in sample app
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/BannerSampleScreen.kt
Labels: bug

#308 NMA-6074: Create a placeholder component for SatsTag
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TagsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTag.kt
Labels: enhancement

#309 NMA-6074: Create placeholder component for Schedule
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ScheduleSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/Schedule.kt
Labels: enhancement

#303 NMA-6039: Create Divider components
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/BrandLogoSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CompletedWorkoutListItemSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/DividersSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SessionDetailsInfoLabelSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SwitchSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/UpcomingWorkoutListItemSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/CompletedWorkoutListItem.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsDivider.kt
Labels: enhancement

#304 NMA-6062: Use Medium Basic in Material 3 tabs
  sats-dna/src/main/kotlin/com/sats/dna/theme/SatsTheme.kt
Labels: bug

#305 NMA-6069: Fix colors for `SatsCard` when in Material 3
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/CardSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsCard.kt
Labels: bug

#306 NMA-6071: Add supporting text support to text fields
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsOutlinedTextField.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsTextField.kt
Labels: enhancement

#307 NMA-6073: Fix button clipping on large font scales
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
  sats-dna/src/main/kotlin/com/sats/dna/tooling/PreviewAnnotations.kt
Labels: bug

#315 NMA-6109: Use Compose BOM
  gradle/libs.versions.toml
Labels: enhancement

#314 Create SATS snackbar visuals and tweak SATS snackbar
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SnackbarSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsSnackbar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbarVisuals.kt
Labels: breaking

#316 NMA-6117: Baseline-shift font styles correctly
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/TopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/typography/SatsTypography.kt
Labels: bug

#321 NMA-6129: Add play icon
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/IconsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/icons/SatsIcons.kt
  sats-dna/src/main/res/drawable/ic_play.xml
Labels: enhancement

#323 NMA-6130: Create bell icon button component
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/appbar/TopAppBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
Labels: enhancement

#324 NMA-6131: Use Material 3 exclusively in Sample App
  sample-app/build.gradle.kts
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/DividersSampleScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/FriendsBookingStatusSampleScreen.kt
Labels: bug

#325 NMA-6134: Add default padding to Sats Screen's snackbar host
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
Labels: bug

#326 NMA-6135: Add default navigation bars padding to SatsScreen
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
Labels: refactor

#327 NMA-6134: Add bottom padding to SatsScreen's snack bar host
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
Labels: bug

#319 NMA-6120: Add new snackbar error theme
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/SnackbarSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbarVisuals.kt
Labels: enhancement

#330 NMA-6140: Rename snackbar to protein bar
  sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/ProteinBarSampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBarVisuals.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbarVisuals.kt
Labels: refactor, breaking

#333 NMA-6142: Add new border colors to outlined text fields
  sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
  sats-dna/src/main/kotlin/com/sats/dna/components/SatsOutlinedTextField.kt
Labels: bug, enhancement
